# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on:
  push:
    branches:
      - master

env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build -PprojVersion=${{github.run_number}}
      - name: prepare
        run: |
          mkdir upload
          mkdir upload/download
          mkdir upload/utils
          cp launcher-bootstrap/build/launch4j/launcher-bootstrap.exe upload/download/launcher.exe
          cp launcher-bootstrap/build/libs/launcher-bootstrap-* upload/download/launcher.jar
          echo "{\"version\":\"${BUILD}\",\"url\":\"https://futuretechcraft.cz/launcher/launcher/launcher.jar\"}" > upload/latest.json
          cp launcher-fancy/build/libs/launcher-fancy-* upload/launcher.jar
          cp creator-tools/build/libs/creator-tools-* upload/creator-tools.jar
          cp launcher-builder/build/libs/launcher-builder-* upload/launcher-builder.jar
        env:
          BUILD: ${{github.run_number}}

      - name: Upload ftp
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: "vestacp.fakaheda.eu"
          protocol: ftps
          username: "fh_387317_launcher"
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "upload/"
          server-dir: "launcher/"